### ISSUE TITLE
Uncaught Error: Objects are not valid as a React child (found: [object File]).

### ISSUE THREAD

**Issue by IlirBajrami** [jasonericdavis/speech-recognition-using-react#2]
Thanks for this sample. 
Im getting this error when uploading file on the Async tab: 

![Screenshot 2021-06-19 at 17 54 00](https://user-images.githubusercontent.com/22265824/122648049-8ded4900-d127-11eb-945f-8dac64025986.png)

and this is my .env file

![Screenshot 2021-06-19 at 17 54 28](https://user-images.githubusercontent.com/22265824/122648072-a52c3680-d127-11eb-8941-1e331094ead4.png)

Im not sure about the WEBHOOK_BASE_URL and MEDIA_PATH.

What am i doing wrong here?

**Comment by jasonericdavis** [comment]
@IlirBajrami I checked in a fix for the error you were seeing above.

For the environment variables:

- WEBHOOK_BASE_URL: This value should be where rev.ai sends the webhook request when processing is complete. As an example when developing and running the server locally I used ngrok as a tunnel to my local machine and set this value as the ngrok URL.
- MEDIA_PATH: This value is where to store the uploaded media files. For example, I have this value set to `public/media/ `

**Comment by IlirBajrami** [comment]
@jasonericdavis  thanks for the reply. 
Now i get the file name after a select a file so the Uncaught Error is fixed. 
But when i  Submit the file i get this error in the console:

![Screenshot 2021-06-19 at 22 24 13](https://user-images.githubusercontent.com/22265824/122654624-15997e80-d14d-11eb-97a1-2e14af233c1e.png)

and this in terminal:

![Screenshot 2021-06-19 at 22 24 34](https://user-images.githubusercontent.com/22265824/122654639-21854080-d14d-11eb-8beb-348628c9c7ec.png)

even though the file now appears in the public/media/ folder and also i get the jobs in the rev.ai dashboard
which means that .env variables are correct.

<img width="1581" alt="Screenshot 2021-06-19 at 22 26 10" src="https://user-images.githubusercontent.com/22265824/122654676-5d200a80-d14d-11eb-981e-ca7c6e985ef0.png">

**Comment by jasonericdavis** [comment]
I updated the `WEBHOOK_BASE_URL` environment variable on my end and received the same error. Could you try changing that value to a `http` protocol and trying again.

**Comment by IlirBajrami** [comment]
Using this `WEBHOOK_BASE_URL` https://api.rev.ai/speechtotext/v1 

i dont get the error in the console and i get the object: 

![Screenshot 2021-06-19 at 23 50 07](https://user-images.githubusercontent.com/22265824/122656259-159f7b80-d159-11eb-99aa-95118569a62f.png)

but i still get the error in terminal: 

![Screenshot 2021-06-19 at 23 50 38](https://user-images.githubusercontent.com/22265824/122656268-27811e80-d159-11eb-9e50-cdc67c1c2281.png)

however i dont get this error in terminal when i upload a file which is already in the /media folder

BUT now i get `failed` in the rev.ai dashboard:

<img width="1650" alt="Screenshot 2021-06-19 at 23 52 20" src="https://user-images.githubusercontent.com/22265824/122656290-64e5ac00-d159-11eb-914b-24372952238b.png">

also i dont get anything returned in UI. should i normally get the transcribed text there or you just console.log-ed it?

**Comment by IlirBajrami** [comment]
When uploading a file which is already in the /media folder, i also get `In progress` in the dashboard:

<img width="1621" alt="Screenshot 2021-06-20 at 00 19 46" src="https://user-images.githubusercontent.com/22265824/122656695-39fd5700-d15d-11eb-8118-7e2c33b74e06.png">

but it stays `In progress` and never changes. when i reload the dashboard it fails just like the other files

**Comment by jasonericdavis** [comment]
It looks like your `WEBHOOK_BASE_URL` may not be correct. Currently, it looks like it is pointing to the rev.ai URL.  That value should point to the server you are running instead. If you are running the server on your local machine you will need a way to expose the server to the internet. I use [ngrok](http://ngrok.com) and I use the ngrok provided URL example (https://140a4f3df18a.ngrok.io) for the value of the `WEBHOOK_BASE_URL` variable

**Comment by IlirBajrami** [comment]
Nice. it works.
Thanks a lot. I'd have to read their documentation now how to get other values from the API so i can display them in the UI.

**Comment by jasonericdavis** [comment]
I'm glad you got it working. If you have any other questions don't hesitate to reach out.

**Comment by jasonericdavis** [comment]
This issue was closed with PR #3
